### ISSUE TITLE
Class or namespace should be renamed

### ISSUE THREAD

**Issue by fagnercarvalho** [trustpilot/nuget-authenticated-encryption#11]
I don't believe that keeping the class and namespace the same (`AuthenticatedEncryption`) is a good idea.

How about we refactor this?

Some references:

- https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1724-type-names-should-not-match-namespaces?view=vs-2019.
- https://stackoverflow.com/a/18731452/1459499.

**Comment by dandago** [comment]
I agree, I have to use `AuthenticatedEncryption.AuthenticatedEncryption.Encrypt(...)` every time.

**Comment by refactorsaurusrex** [comment]
Hey @spewu, would you accept a PR if I make these changes? I could fork and create a separate nuget package, but I'd rather not do that just for a namespace change. Thanks in advance!

**Comment by spewu** [comment]
@refactorsaurusrex Thanks for mentioning me here - I had not seen this issue. I no longer work in Trustpilot, but I am pretty confident that I can get your PR merged if you create one

**Comment by refactorsaurusrex** [comment]
Great! I'll get on that soon.

**Comment by irq** [comment]
The package has now been updated thanks to @refactorsaurusrex 👍
